# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xiaoyao/Desktop/mySoftRender

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xiaoyao/Desktop/mySoftRender/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xiaoyao/Desktop/mySoftRender/build/CMakeFiles /home/xiaoyao/Desktop/mySoftRender/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xiaoyao/Desktop/mySoftRender/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stb_image_wrapper

# Build rule for target.
stb_image_wrapper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb_image_wrapper
.PHONY : stb_image_wrapper

# fast build rule for target.
stb_image_wrapper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb_image_wrapper.dir/build.make CMakeFiles/stb_image_wrapper.dir/build
.PHONY : stb_image_wrapper/fast

#=============================================================================
# Target rules for targets named imgui_sdl

# Build rule for target.
imgui_sdl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui_sdl
.PHONY : imgui_sdl

# fast build rule for target.
imgui_sdl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/build
.PHONY : imgui_sdl/fast

#=============================================================================
# Target rules for targets named mySoftRender

# Build rule for target.
mySoftRender: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mySoftRender
.PHONY : mySoftRender

# fast build rule for target.
mySoftRender/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mySoftRender.dir/build.make CMakeFiles/mySoftRender.dir/build
.PHONY : mySoftRender/fast

#=============================================================================
# Target rules for targets named glm

# Build rule for target.
glm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glm
.PHONY : glm

# fast build rule for target.
glm/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glm-build/glm/CMakeFiles/glm.dir/build.make _deps/glm-build/glm/CMakeFiles/glm.dir/build
.PHONY : glm/fast

_deps/imgui-src/backends/imgui_impl_sdl2.o: _deps/imgui-src/backends/imgui_impl_sdl2.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/backends/imgui_impl_sdl2.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.cpp.o

_deps/imgui-src/backends/imgui_impl_sdl2.i: _deps/imgui-src/backends/imgui_impl_sdl2.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/backends/imgui_impl_sdl2.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.cpp.i

_deps/imgui-src/backends/imgui_impl_sdl2.s: _deps/imgui-src/backends/imgui_impl_sdl2.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/backends/imgui_impl_sdl2.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdl2.cpp.s

_deps/imgui-src/backends/imgui_impl_sdlrenderer2.o: _deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer2.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.o

_deps/imgui-src/backends/imgui_impl_sdlrenderer2.i: _deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer2.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.i

_deps/imgui-src/backends/imgui_impl_sdlrenderer2.s: _deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer2.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_sdlrenderer2.cpp.s

_deps/imgui-src/imgui.o: _deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.o

# target to build an object file
_deps/imgui-src/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.cpp.o

_deps/imgui-src/imgui.i: _deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.i

# target to preprocess a source file
_deps/imgui-src/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.cpp.i

_deps/imgui-src/imgui.s: _deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.s

# target to generate assembly for a file
_deps/imgui-src/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.cpp.s

_deps/imgui-src/imgui_demo.o: _deps/imgui-src/imgui_demo.cpp.o
.PHONY : _deps/imgui-src/imgui_demo.o

# target to build an object file
_deps/imgui-src/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui_demo.cpp.o
.PHONY : _deps/imgui-src/imgui_demo.cpp.o

_deps/imgui-src/imgui_demo.i: _deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.i

# target to preprocess a source file
_deps/imgui-src/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui_demo.cpp.i
.PHONY : _deps/imgui-src/imgui_demo.cpp.i

_deps/imgui-src/imgui_demo.s: _deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.s

# target to generate assembly for a file
_deps/imgui-src/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui_demo.cpp.s
.PHONY : _deps/imgui-src/imgui_demo.cpp.s

_deps/imgui-src/imgui_draw.o: _deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.o

# target to build an object file
_deps/imgui-src/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.cpp.o

_deps/imgui-src/imgui_draw.i: _deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.i

# target to preprocess a source file
_deps/imgui-src/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.cpp.i

_deps/imgui-src/imgui_draw.s: _deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.s

# target to generate assembly for a file
_deps/imgui-src/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.cpp.s

_deps/imgui-src/imgui_tables.o: _deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.o

# target to build an object file
_deps/imgui-src/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.cpp.o

_deps/imgui-src/imgui_tables.i: _deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.i

# target to preprocess a source file
_deps/imgui-src/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.cpp.i

_deps/imgui-src/imgui_tables.s: _deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.s

# target to generate assembly for a file
_deps/imgui-src/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.cpp.s

_deps/imgui-src/imgui_widgets.o: _deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.o

# target to build an object file
_deps/imgui-src/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.cpp.o

_deps/imgui-src/imgui_widgets.i: _deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.i

# target to preprocess a source file
_deps/imgui-src/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.cpp.i

_deps/imgui-src/imgui_widgets.s: _deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.s

# target to generate assembly for a file
_deps/imgui-src/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_sdl.dir/build.make CMakeFiles/imgui_sdl.dir/_deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mySoftRender.dir/build.make CMakeFiles/mySoftRender.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mySoftRender.dir/build.make CMakeFiles/mySoftRender.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mySoftRender.dir/build.make CMakeFiles/mySoftRender.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/software_renderer.o: src/software_renderer.cpp.o
.PHONY : src/software_renderer.o

# target to build an object file
src/software_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mySoftRender.dir/build.make CMakeFiles/mySoftRender.dir/src/software_renderer.cpp.o
.PHONY : src/software_renderer.cpp.o

src/software_renderer.i: src/software_renderer.cpp.i
.PHONY : src/software_renderer.i

# target to preprocess a source file
src/software_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mySoftRender.dir/build.make CMakeFiles/mySoftRender.dir/src/software_renderer.cpp.i
.PHONY : src/software_renderer.cpp.i

src/software_renderer.s: src/software_renderer.cpp.s
.PHONY : src/software_renderer.s

# target to generate assembly for a file
src/software_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mySoftRender.dir/build.make CMakeFiles/mySoftRender.dir/src/software_renderer.cpp.s
.PHONY : src/software_renderer.cpp.s

src/stb_image_impl.o: src/stb_image_impl.cpp.o
.PHONY : src/stb_image_impl.o

# target to build an object file
src/stb_image_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb_image_wrapper.dir/build.make CMakeFiles/stb_image_wrapper.dir/src/stb_image_impl.cpp.o
.PHONY : src/stb_image_impl.cpp.o

src/stb_image_impl.i: src/stb_image_impl.cpp.i
.PHONY : src/stb_image_impl.i

# target to preprocess a source file
src/stb_image_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb_image_wrapper.dir/build.make CMakeFiles/stb_image_wrapper.dir/src/stb_image_impl.cpp.i
.PHONY : src/stb_image_impl.cpp.i

src/stb_image_impl.s: src/stb_image_impl.cpp.s
.PHONY : src/stb_image_impl.s

# target to generate assembly for a file
src/stb_image_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stb_image_wrapper.dir/build.make CMakeFiles/stb_image_wrapper.dir/src/stb_image_impl.cpp.s
.PHONY : src/stb_image_impl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... glm"
	@echo "... imgui_sdl"
	@echo "... mySoftRender"
	@echo "... stb_image_wrapper"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl2.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl2.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdl2.s"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdlrenderer2.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdlrenderer2.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_sdlrenderer2.s"
	@echo "... _deps/imgui-src/imgui.o"
	@echo "... _deps/imgui-src/imgui.i"
	@echo "... _deps/imgui-src/imgui.s"
	@echo "... _deps/imgui-src/imgui_demo.o"
	@echo "... _deps/imgui-src/imgui_demo.i"
	@echo "... _deps/imgui-src/imgui_demo.s"
	@echo "... _deps/imgui-src/imgui_draw.o"
	@echo "... _deps/imgui-src/imgui_draw.i"
	@echo "... _deps/imgui-src/imgui_draw.s"
	@echo "... _deps/imgui-src/imgui_tables.o"
	@echo "... _deps/imgui-src/imgui_tables.i"
	@echo "... _deps/imgui-src/imgui_tables.s"
	@echo "... _deps/imgui-src/imgui_widgets.o"
	@echo "... _deps/imgui-src/imgui_widgets.i"
	@echo "... _deps/imgui-src/imgui_widgets.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/software_renderer.o"
	@echo "... src/software_renderer.i"
	@echo "... src/software_renderer.s"
	@echo "... src/stb_image_impl.o"
	@echo "... src/stb_image_impl.i"
	@echo "... src/stb_image_impl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

